title: "Chien-Hsiang"
description: > 
  <p style="text-align:center;">“You cannot swim for new horizons until you have courage to lose sight of the shore.”</p>
  <p style="text-align:right;">– William Faulkner</p>
email: hsuchienhsiang@gmail.com
github_username: chienhsiang
url: "https://chienhsiang.github.io/"
markdown: kramdown
theme: jekyll-theme-tactile
excerpt_separator: <!--more-->