title: "Chien-Hsiang"
description: > 
  <br>
  <a href="/" style="color:#A9A9A9;">Home</a> &ensp; 
  <a href="/blog/" style="color:#A9A9A9;">Blog</a>
email: hsuchienhsiang@gmail.com
github_username: chienhsiang
url: "https://chienhsiang.github.io/"
markdown: kramdown
# theme: minima
theme: jekyll-theme-tactile
